### ISSUE TITLE
inode/x-empty

### ISSUE THREAD

**Issue by CoR--** [shanept/MimeSniffer#1]
Class is really excellent!
It lacks case if file size is 0. In that case it should return inode/x-empty as a type. 

I added this:

``` php
protected function sniff_empty() {

    if (strlen($this->header) === 0) {

        $this->detected_type    = 'inode/x-empty';
        return true;
    }

    return false;   
}

// should be first
protected function detect_type() {
    if ( $this->sniff_empty() )     return;
    if ( $this->sniff_images() )    return;
 ...
}
```

**Comment by shanept** [comment]
CoR, thanks for your input and kind words, they are much appreciated.
I shall push those changes as soon as I have a moment, thank you.
